toolbar_location: top
toolbar_align: left
statusbar_location: bottom
toolbar1: newdocument fullpage | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | styleselect formatselect fontselect fontsizeselect
toolbar2: cut copy paste | searchreplace | bullist numlist | outdent indent blockquote | undo redo | link unlink anchor image media code | insertdatetime preview | forecolor backcolor
toolbar3: table | hr removeformat | subscript superscript | charmap emoticons | print fullscreen | ltr rtl | spellchecker | visualchars visualblocks nonbreaking template pagebreak restoredraft
plugins: 
  - autolink 
  - link
  - image 
  - lists 
  - charmap 
  - print 
  - preview 
  - hr 
  - anchor
  - pagebreak 
  - spellchecker
  - searchreplace 
  - wordcount 
  - visualblocks 
  - visualchars 
  - code 
  - media 
  - nonbreaking
  - table 
  - contextmenu 
  - directionality 
  - emoticons
  - template
  - textcolor
  - colorpicker
